### ISSUE TITLE
[REQUEST]

### ISSUE THREAD

**Issue by matte-oss** [0nTheGoRepairs/Thinkpad-T450s-Opencore-0.8-English-Intel-WIFI-Monterey-Hackintosh#2]
Is there a stable fully-working Sonoma efi?

**Comment by 0nTheGoRepairs** [comment]
I have not found one that works that well, and making one is frankly over my head. For now I recommend using Mac OS Monterey. If I come across anything that is reliable, it will be posted.

**Comment by matte-oss** [comment]
Ok thank you!
